/**
 * Webhook Integration Tests
 *
 * Tests the complete webhook flow including:
 * - Webhook CRUD operations
 * - Webhook event triggering
 * - Webhook delivery
 */

import request from 'supertest';
import { Application } from 'express';
import { prisma } from '../database/client';
import { createServer } from '../server';
import { container } from '../services/container';

describe('Webhook Integration Tests', () => {
  let app: Application;

  beforeAll(async () => {
    app = await createServer();
  });

  afterAll(async () => {
    // Clean up test data
    await prisma.webhookEvent.deleteMany({
      where: {
        webhook: {
          url: { contains: 'webhook-test-' },
        },
      },
    });

    await prisma.webhook.deleteMany({
      where: { url: { contains: 'webhook-test-' } },
    });

    await prisma.user.deleteMany({
      where: { email: { contains: 'webhook-int-' } },
    });

    await prisma.organization.deleteMany({
      where: { email: { contains: 'webhook-int-' } },
    });

    await prisma.$disconnect();
  });

  const registerTestOrg = async () => {
    const unique = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
    const email = `webhook-int-${unique}@example.com`;
    const organizationName = `Webhook Integration Org ${unique}`;

    const response = await request(app)
      .post('/v1/auth/register')
      .send({
        email,
        password: 'SecurePass123',
        organizationName,
      })
      .expect(201);

    return {
      token: response.body.data.token as string,
      organizationId: response.body.data.organization.id as string,
    };
  };

  const createWebhook = async (
    token: string,
    overrides: Partial<{ url: string; events: string[]; secret: string }> = {}
  ) => {
    const unique = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
    const payload = {
      url: overrides.url ?? `https://webhook-test-${unique}.example.com/webhook`,
      events: overrides.events ?? ['transaction.completed', 'transaction.failed'],
      ...(overrides.secret && { secret: overrides.secret }),
    };

    const response = await request(app)
      .post('/v1/webhooks')
      .set('Authorization', `Bearer ${token}`)
      .send(payload)
      .expect(201);

    return {
      webhook: response.body.data,
      payload,
    };
  };

  describe('POST /v1/webhooks', () => {
    it('creates a new webhook for the organization', async () => {
      const { token, organizationId } = await registerTestOrg();

      const { webhook, payload } = await createWebhook(token);

      expect(webhook.organizationId).toBe(organizationId);
      expect(webhook.url).toBe(payload.url);
      expect(webhook.events).toEqual(payload.events);
      expect(webhook.enabled).toBe(true);
      expect(webhook.secret).toBeUndefined(); // Secret should not be returned
      expect(webhook.id).toBeDefined();
    });

    it('generates a secret if not provided', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token, {});

      // Secret should not be in response, but webhook should exist
      expect(webhook.secret).toBeUndefined();
      expect(webhook.id).toBeDefined();

      // Verify secret was generated by checking database
      const dbWebhook = await prisma.webhook.findUnique({
        where: { id: webhook.id },
      });
      expect(dbWebhook?.secret).toBeDefined();
      expect(dbWebhook?.secret.length).toBeGreaterThanOrEqual(16);
    });

    it('uses provided secret if given', async () => {
      const { token } = await registerTestOrg();
      const customSecret = 'my-custom-webhook-secret-key-12345';

      const { webhook } = await createWebhook(token, { secret: customSecret });

      // Verify secret was saved
      const dbWebhook = await prisma.webhook.findUnique({
        where: { id: webhook.id },
      });
      expect(dbWebhook?.secret).toBe(customSecret);
    });

    it('rejects invalid URLs', async () => {
      const { token } = await registerTestOrg();

      const response = await request(app)
        .post('/v1/webhooks')
        .set('Authorization', `Bearer ${token}`)
        .send({
          url: 'not-a-valid-url',
          events: ['transaction.completed'],
        })
        .expect(400);

      expect(response.body.success).toBe(false);
      expect(response.body.error).toBe('BAD_REQUEST');
    });

    it('rejects empty events array', async () => {
      const { token } = await registerTestOrg();

      const response = await request(app)
        .post('/v1/webhooks')
        .set('Authorization', `Bearer ${token}`)
        .send({
          url: 'https://example.com/webhook',
          events: [],
        })
        .expect(400);

      expect(response.body.success).toBe(false);
    });

    it('rejects invalid event types', async () => {
      const { token } = await registerTestOrg();

      const response = await request(app)
        .post('/v1/webhooks')
        .set('Authorization', `Bearer ${token}`)
        .send({
          url: 'https://example.com/webhook',
          events: ['invalid.event.type'],
        })
        .expect(400);

      expect(response.body.success).toBe(false);
    });

    it('requires authentication', async () => {
      const response = await request(app)
        .post('/v1/webhooks')
        .send({
          url: 'https://example.com/webhook',
          events: ['transaction.completed'],
        })
        .expect(401);

      expect(response.body.success).toBe(false);
    });
  });

  describe('GET /v1/webhooks', () => {
    it('lists webhooks for the organization', async () => {
      const { token, organizationId } = await registerTestOrg();

      // Create multiple webhooks
      const { webhook: webhook1 } = await createWebhook(token);
      const { webhook: webhook2 } = await createWebhook(token);

      const response = await request(app)
        .get('/v1/webhooks')
        .set('Authorization', `Bearer ${token}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(Array.isArray(response.body.data)).toBe(true);
      expect(response.body.data.length).toBeGreaterThanOrEqual(2);

      // Verify all webhooks belong to the organization
      response.body.data.forEach((webhook: any) => {
        expect(webhook.organizationId).toBe(organizationId);
        expect(webhook.secret).toBeUndefined(); // Secrets should not be returned
      });

      // Verify our created webhooks are in the list
      const webhookIds = response.body.data.map((w: any) => w.id);
      expect(webhookIds).toContain(webhook1.id);
      expect(webhookIds).toContain(webhook2.id);
    });

    it('filters by enabled status', async () => {
      const { token } = await registerTestOrg();

      const { webhook: enabledWebhook } = await createWebhook(token);

      // Disable the webhook
      await request(app)
        .patch(`/v1/webhooks/${enabledWebhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ enabled: false })
        .expect(200);

      // Create another enabled webhook
      const { webhook: enabledWebhook2 } = await createWebhook(token);

      // Get only enabled webhooks
      const response = await request(app)
        .get('/v1/webhooks?enabled=true')
        .set('Authorization', `Bearer ${token}`)
        .expect(200);

      const enabledWebhooks = response.body.data.filter((w: any) => w.enabled === true);
      expect(enabledWebhooks.length).toBeGreaterThanOrEqual(1);
      expect(enabledWebhooks.some((w: any) => w.id === enabledWebhook2.id)).toBe(true);
      expect(enabledWebhooks.some((w: any) => w.id === enabledWebhook.id)).toBe(false);

      // Get only disabled webhooks
      const disabledResponse = await request(app)
        .get('/v1/webhooks?enabled=false')
        .set('Authorization', `Bearer ${token}`)
        .expect(200);

      const disabledWebhooks = disabledResponse.body.data.filter((w: any) => w.enabled === false);
      expect(disabledWebhooks.some((w: any) => w.id === enabledWebhook.id)).toBe(true);
    });

    it('requires authentication', async () => {
      const response = await request(app).get('/v1/webhooks').expect(401);

      expect(response.body.success).toBe(false);
    });
  });

  describe('GET /v1/webhooks/:id', () => {
    it('returns webhook details', async () => {
      const { token, organizationId } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .get(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.id).toBe(webhook.id);
      expect(response.body.data.organizationId).toBe(organizationId);
      expect(response.body.data.url).toBe(webhook.url);
      expect(response.body.data.secret).toBeUndefined(); // Secret should not be returned
    });

    it('returns 404 for non-existent webhook', async () => {
      const { token } = await registerTestOrg();
      const fakeId = '00000000-0000-0000-0000-000000000000';

      const response = await request(app)
        .get(`/v1/webhooks/${fakeId}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(404);

      expect(response.body.success).toBe(false);
      expect(response.body.error).toBe('NOT_FOUND');
    });

    it('returns 404 for webhook from different organization', async () => {
      const { token: token1 } = await registerTestOrg();
      const { token: token2 } = await registerTestOrg();

      const { webhook } = await createWebhook(token1);

      const response = await request(app)
        .get(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token2}`)
        .expect(404);

      expect(response.body.success).toBe(false);
    });

    it('requires authentication', async () => {
      const { token } = await registerTestOrg();
      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .get(`/v1/webhooks/${webhook.id}`)
        .expect(401);

      expect(response.body.success).toBe(false);
    });
  });

  describe('PATCH /v1/webhooks/:id', () => {
    it('updates webhook URL', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);
      const newUrl = 'https://new-webhook-url.example.com/webhook';

      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ url: newUrl })
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.url).toBe(newUrl);
      expect(response.body.data.events).toEqual(webhook.events); // Events should remain unchanged
    });

    it('updates webhook events', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);
      const newEvents = ['transaction.completed'];

      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ events: newEvents })
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.events).toEqual(newEvents);
      expect(response.body.data.url).toBe(webhook.url); // URL should remain unchanged
    });

    it('updates webhook enabled status', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      // Disable webhook
      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ enabled: false })
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.enabled).toBe(false);

      // Re-enable webhook
      const response2 = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ enabled: true })
        .expect(200);

      expect(response2.body.data.enabled).toBe(true);
    });

    it('updates multiple fields at once', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);
      const newUrl = 'https://updated-webhook.example.com/webhook';
      const newEvents = ['transaction.failed'];

      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({
          url: newUrl,
          events: newEvents,
          enabled: false,
        })
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.url).toBe(newUrl);
      expect(response.body.data.events).toEqual(newEvents);
      expect(response.body.data.enabled).toBe(false);
    });

    it('rejects invalid URL', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ url: 'invalid-url' })
        .expect(400);

      expect(response.body.success).toBe(false);
    });

    it('returns 404 for non-existent webhook', async () => {
      const { token } = await registerTestOrg();
      const fakeId = '00000000-0000-0000-0000-000000000000';

      const response = await request(app)
        .patch(`/v1/webhooks/${fakeId}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ url: 'https://example.com/webhook' })
        .expect(404);

      expect(response.body.success).toBe(false);
    });

    it('requires authentication', async () => {
      const { token } = await registerTestOrg();
      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .patch(`/v1/webhooks/${webhook.id}`)
        .send({ url: 'https://example.com/webhook' })
        .expect(401);

      expect(response.body.success).toBe(false);
    });
  });

  describe('DELETE /v1/webhooks/:id', () => {
    it('deletes a webhook', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .delete(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(200);

      expect(response.body.success).toBe(true);

      // Verify webhook is deleted
      const getResponse = await request(app)
        .get(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(404);

      expect(getResponse.body.success).toBe(false);
    });

    it('returns 404 for non-existent webhook', async () => {
      const { token } = await registerTestOrg();
      const fakeId = '00000000-0000-0000-0000-000000000000';

      const response = await request(app)
        .delete(`/v1/webhooks/${fakeId}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(404);

      expect(response.body.success).toBe(false);
    });

    it('returns 404 for webhook from different organization', async () => {
      const { token: token1 } = await registerTestOrg();
      const { token: token2 } = await registerTestOrg();

      const { webhook } = await createWebhook(token1);

      const response = await request(app)
        .delete(`/v1/webhooks/${webhook.id}`)
        .set('Authorization', `Bearer ${token2}`)
        .expect(404);

      expect(response.body.success).toBe(false);
    });

    it('requires authentication', async () => {
      const { token } = await registerTestOrg();
      const { webhook } = await createWebhook(token);

      const response = await request(app)
        .delete(`/v1/webhooks/${webhook.id}`)
        .expect(401);

      expect(response.body.success).toBe(false);
    });
  });

  describe('Webhook Service Integration', () => {
    it('finds enabled webhooks by event type', async () => {
      const { token, organizationId } = await registerTestOrg();

      // Create webhooks for different events
      const { webhook: webhook1 } = await createWebhook(token, {
        events: ['transaction.completed'],
      });
      const { webhook: webhook2 } = await createWebhook(token, {
        events: ['transaction.completed', 'transaction.failed'],
      });
      const { webhook: webhook3 } = await createWebhook(token, {
        events: ['transaction.failed'],
      });

      // Disable one webhook
      await request(app)
        .patch(`/v1/webhooks/${webhook3.id}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ enabled: false })
        .expect(200);

      // Find enabled webhooks for transaction.completed
      const webhooks = await container.webhookRepository.findEnabledByEvent(
        organizationId,
        'transaction.completed'
      );

      expect(webhooks.length).toBe(2);
      const webhookIds = webhooks.map((w) => w.id);
      expect(webhookIds).toContain(webhook1.id);
      expect(webhookIds).toContain(webhook2.id);
      expect(webhookIds).not.toContain(webhook3.id); // Disabled webhook should not be included

      // All returned webhooks should be enabled
      webhooks.forEach((webhook) => {
        expect(webhook.enabled).toBe(true);
      });
    });

    it('creates webhook event log entries', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      // Create an event log entry
      const eventLog = await container.webhookRepository.createEvent({
        webhookId: webhook.id,
        eventType: 'transaction.completed',
        payload: { test: 'data' },
      });

      expect(eventLog.id).toBeDefined();
      expect(eventLog.webhookId).toBe(webhook.id);
      expect(eventLog.eventType).toBe('transaction.completed');
      expect(eventLog.payload).toEqual({ test: 'data' });
      expect(eventLog.delivered).toBe(false);
      expect(eventLog.attempts).toBe(0);
    });

    it('updates webhook event delivery status', async () => {
      const { token } = await registerTestOrg();

      const { webhook } = await createWebhook(token);

      // Create an event log entry
      const eventLog = await container.webhookRepository.createEvent({
        webhookId: webhook.id,
        eventType: 'transaction.completed',
        payload: { test: 'data' },
      });

      // Update delivery status
      await container.webhookRepository.updateEventDelivery(eventLog.id, {
        responseStatus: 200,
        responseBody: 'OK',
        delivered: true,
        attempts: 1,
      });

      // Verify update
      const updatedEvent = await prisma.webhookEvent.findUnique({
        where: { id: eventLog.id },
      });

      expect(updatedEvent?.responseStatus).toBe(200);
      expect(updatedEvent?.responseBody).toBe('OK');
      expect(updatedEvent?.delivered).toBe(true);
      expect(updatedEvent?.attempts).toBe(1);
      expect(updatedEvent?.deliveredAt).toBeDefined();
    });
  });
});

